language: ruby
rvm:
  - 2.1.2
  - 2.1.5
  - 2.2.1

services:
  - mongodb

script: ./.travis/execute.sh

notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change

branches:
  only:
    - master
    - develop
