test:
  host: <%= ENV['TEST_DB_HOST'] || 'localhost' %>
  database: cypress_test

development:
  host: localhost
  database: cypress_development

# set these environment variables on your prod server
production:
  host: localhost
  port: 27017
  database: cypress_production